import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';

const XP = {series:20, block:40, session:100, record:50, quest:100, boss:500};
const COLORS = {violet:'#a66cff', red:'#ff4d62', gold:'#f7c94c', green:'#53df99'};
const SESSIONS = [
 {id:'upper-a',name:'UPPER A',focus:'Pecs · Bras',color:'violet',icon:'✦',blocks:[
  {rest:90, ex:[['Pompes',3,8,20,'Force'],['Tractions',3,5,15,'Force']]}, {rest:75,ex:[['Dips',3,6,15,'Force'],['Rowing inversé',3,8,15,'Résistance']]}, {rest:0,ex:[['Curl haltères',3,8,15,'Force'],['Extension triceps',3,8,15,'Endurance']]}]},
 {id:'lower-a',name:'LOWER A',focus:'Quadriceps',color:'red',icon:'◆',blocks:[
  {rest:90,ex:[['Squats',3,10,20,'Force'],['Fentes',3,8,15,'Résistance']]}, {rest:75,ex:[['Squat bulgare',2,8,15,'Force'],['Wall sit',2,20,60,'Endurance']]}, {rest:0,ex:[['Mollets',2,12,25,'Explosivité']]}]},
 {id:'upper-b',name:'UPPER B',focus:'Épaules · Dos',color:'gold',icon:'✷',blocks:[
  {rest:90,ex:[['Pike push-ups',3,6,15,'Force'],['Tractions supination',3,5,15,'Force']]}, {rest:75,ex:[['Élévations latérales',3,10,20,'Endurance'],['Superman',3,10,20,'Résistance']]}, {rest:75,ex:[['Face pulls élastique',3,10,20,'Résistance'],['Planche',2,30,60,'Endurance']]}]},
 {id:'lower-b',name:'LOWER B',focus:'Ischios · Fessiers',color:'green',icon:'✹',blocks:[
  {rest:90,ex:[['Hip thrust',3,10,20,'Force'],['Soulevé de terre une jambe',3,8,15,'Résistance']]}, {rest:75,ex:[['Nordic curl assisté',3,5,12,'Force'],['Fentes arrière',3,8,15,'Explosivité']]}, {rest:0,ex:[['Pont fessier',2,15,25,'Endurance'],['Mollets',2,12,25,'Explosivité']]}]}
];
const defaultData={xp:0, history:[], proposals:{}, bossHp:10000, claimed:[], title:'L’Initiée', restDays:[0,2,4,6]};
const load=()=>{try{return {...defaultData,...JSON.parse(localStorage.getItem('ascend-v1'))}}catch{return defaultData}};
const save=d=>localStorage.setItem('ascend-v1',JSON.stringify(d));
const totalSets=s=>s.blocks.flatMap(b=>b.ex).reduce((n,e)=>n+e[1],0);
const sum=(a,key)=>a.reduce((n,x)=>n+(x[key]||0),0);
const levelFor=xp=>{let l=1, need=350; while(xp>=need){xp-=need;l++;need=300+l*100}return {level:l,inLevel:xp,need}};
const rankFor=l=>['NOVICE','INITIÉ','COMBATTANT','GUERRIER','ÉLITE','MAÎTRE','GRAND MAÎTRE','LÉGENDE'][Math.min(7,Math.floor((l-1)/5))];
function PixelCharacter({type='hero',size='normal'}){return <div className={`pixel-character ${type} ${size}`} aria-label="Sprite pixel art"><i/><b/><em/></div>}
function Bar({value,max=100,color='var(--violet)'}){return <div className="bar"><span style={{width:`${Math.min(100,value/max*100)}%`,background:color}}/></div>}
function Frame({children,className='',...props}){return <section className={`frame ${className}`} {...props}>{children}</section>}
function Nav({page,setPage}){let items=[['home','⌂','Accueil'],['sessions','⚔','Séances'],['stats','▥','Stats'],['map','✧','Carte'],['quests','♛','Quêtes'],['profile','◉','Profil']];return <nav><div className="brand"><span>▲</span> ASCEND<small>FITNESS RPG</small></div><div className="navlinks">{items.map(([id,ic,label])=><button key={id} onClick={()=>setPage(id)} className={page===id?'active':''}><i>{ic}</i>{label}</button>)}</div><div className="nav-footer">V1.0 · LOCAL SAVE<br/><span>● SYSTEM ONLINE</span></div></nav>}
function Layout({children,page,setPage,data}){return <><Nav page={page} setPage={setPage}/><main>{children}</main><div className="mobile-nav">{[['home','⌂'],['sessions','⚔'],['stats','▥'],['map','✧'],['profile','◉']].map(x=><button onClick={()=>setPage(x[0])} className={page===x[0]?'active':''} key={x[0]}>{x[1]}</button>)}</div></>}
function Header({label,sub,children}){return <header><div><p className="eyebrow">{sub||'CHAPITRE I · L’ASCENSION'}</p><h1>{label}</h1></div>{children}</header>}
function Dashboard({data,start}){let lev=levelFor(data.xp), next=SESSIONS[data.history.length%4], quests=questList(data); return <><Header label="LE SANCTUAIRE"><div className="xp-top">NIV. {lev.level}<Bar value={lev.inLevel} max={lev.need}/><small>{lev.inLevel} / {lev.need} XP</small></div></Header><div className="dashboard-grid"><Frame className="hero"><div className="hero-copy"><span className="rank">{rankFor(lev.level)}</span><h2>PRÊT À<br/>T’ÉLEVER ?</h2><p>Chaque répétition forge la légende.</p><button className="button primary" onClick={()=>start(next)}>COMMENCER <b>→</b></button></div><PixelCharacter size="large"/><div className="glow-orb"/></Frame><Frame className="next-session"><p className="eyebrow">PROCHAINE ÉPREUVE</p><div className="session-line"><span style={{color:COLORS[next.color]}}>{next.icon}</span><div><h3>{next.name}</h3><p>{next.focus} · {totalSets(next)} SÉRIES</p></div></div><button className="button ghost" onClick={()=>start(next)}>ENTRER EN SÉANCE</button></Frame><Frame className="streak"><span>🔥</span><div><b>{streak(data.history,data.restDays)}</b><small>JOURS D’ASCENSION</small></div><p>Repos planifié protégé</p></Frame><Frame className="mini-quests"><div className="frame-title">QUÊTES ACTIVES <span>→</span></div>{quests.slice(0,3).map(q=><QuestLine key={q.id} q={q}/>)}</Frame></div></>}
function Sessions({start,data}){return <><Header label="LES ÉPREUVES" sub="PROGRAMME PDC · 4 JOURS"/><div className="session-grid">{SESSIONS.map(s=><Frame className="session-card" key={s.id} style={{'--energy':COLORS[s.color]}}><div className="card-sprite"><PixelCharacter type={s.color}/></div><span className="session-number">0{SESSIONS.indexOf(s)+1}</span><p className="eyebrow">{s.focus}</p><h2>{s.name}</h2><p>{totalSets(s)} séries · {s.blocks.length} blocs</p><div className="exercise-tags">{s.blocks.flatMap(b=>b.ex).slice(0,3).map(e=><span key={e[0]}>{e[0]}</span>)}</div><button className="button" onClick={()=>start(s)}>DÉMARRER →</button></Frame>)}</div><History data={data}/></>}
function Training({session,finish,back,data}){const ordered=useMemo(()=>session.blocks.flatMap((b,bi)=>b.ex.flatMap((e,ei)=>Array.from({length:e[1]},(_,si)=>({b,bi,e,ei,si})))),[session]); const [idx,setIdx]=useState(0),[reps,setReps]=useState(''),[records,setRecords]=useState([]),[rest,setRest]=useState(null),[paused,setPaused]=useState(false),[toast,setToast]=useState(''); let cur=ordered[idx]; useEffect(()=>{if(rest===null||paused)return; if(rest<=0){setRest(null);return}let t=setTimeout(()=>setRest(r=>r-1),1000);return()=>clearTimeout(t)},[rest,paused]); if(rest!==null)return <Rest seconds={rest} setSeconds={setRest} paused={paused} setPaused={setPaused} color={COLORS[session.color]}/>; let proposed=data.proposals[cur.e[0]]?.[cur.si]??cur.e[2]; const validate=()=>{let n=Math.max(0,Number(reps)||0), row={exercise:cur.e[0],reps:n,stat:cur.e[4],target:proposed}; let updated=[...records,row];setRecords(updated);setToast(`+${XP.series} XP · SÉRIE VALIDÉE`);setReps('');setTimeout(()=>setToast(''),950);let isLastOfBlock=idx===ordered.length-1||ordered[idx+1].bi!==cur.bi;if(idx===ordered.length-1){finish(session,updated);return}if(isLastOfBlock){setRest(session.blocks[cur.bi].rest); setPaused(false)}setIdx(idx+1)};return <div className="training" style={{'--energy':COLORS[session.color]}}><header><button className="back" onClick={back}>← QUITTER</button><div className="training-progress">{session.name}<Bar value={idx} max={ordered.length} color="var(--energy)"/><small>{String(idx+1).padStart(2,'0')} / {ordered.length} SÉRIES</small></div></header><div className="workout-stage"><p className="eyebrow">BLOC {cur.bi+1} · {cur.ei===0?'A':'B'}</p><span className="exercise-code">{cur.bi+1}{cur.ei===0?'A':'B'}</span><h1>{cur.e[0]}</h1><div className="target"><span>OBJECTIF</span><b>{cur.e[2]} — {cur.e[3]}</b><small>Proposé : {proposed} reps</small></div><p className="series-count">SÉRIE {cur.si+1} / {cur.e[1]}</p><input autoFocus type="number" inputMode="numeric" value={reps} onChange={e=>setReps(e.target.value)} onKeyDown={e=>e.key==='Enter'&&validate()} placeholder={String(proposed)}/><button className="button primary validate" onClick={validate}>VALIDER <span>+{XP.series} XP</span></button><p className="hint">Valide avec Entrée</p></div>{toast&&<div className="xp-toast">{toast}</div>}</div>}
function Rest({seconds,setSeconds,paused,setPaused,color}){let m=String(Math.floor(seconds/60)).padStart(2,'0'),s=String(seconds%60).padStart(2,'0');return <div className="rest-screen" style={{'--energy':color}}><p className="eyebrow">RÉCUPÉRATION · BLOC TERMINÉ +{XP.block} XP</p><PixelCharacter type="specter"/><h1>{seconds===0?'GO !':`${m}:${s}`}</h1><h2>{seconds===0?'L’ÉPREUVE CONTINUE':'REPOS'}</h2><div><button className="button primary" onClick={()=>setPaused(!paused)}>{paused?'REPRENDRE':'PAUSE'}</button><button className="button ghost" onClick={()=>setSeconds(0)}>PASSER</button></div></div>}
function Results({result,continueTo}){return <div className="results"><div className="victory-sparkles">✦ ✧ ✦</div><p className="eyebrow">ÉPREUVE ACCOMPLIE</p><h1>SÉANCE<br/><em>TERMINÉE</em></h1><PixelCharacter type="hero" size="large"/><Frame><h2>{result.session.name}</h2><div className="result-numbers"><div><b>{result.records.length}</b><span>SÉRIES</span></div><div><b>{sum(result.records,'reps')}</b><span>REPS</span></div><div><b>+{result.xp}</b><span>XP</span></div><div><b>-{result.damage}</b><span>DÉGÂTS</span></div></div><p className="reward-line">🔥 STREAK {result.streak} · +{result.statGain} {result.stat}</p><button className="button primary" onClick={continueTo}>RETOURNER AU SANCTUAIRE →</button></Frame></div>}
function questList(data){let h=data.history, total=h.length,reps=sum(h,'reps'), enemies=Math.floor((10000-data.bossHp)/500);return [{id:'daily',title:'Rituel du jour',desc:'Terminer une séance',value:Math.min(1,h.filter(x=>new Date(x.date).toDateString()===new Date().toDateString()).length),max:1,xp:100,rarity:'COMMUN'},{id:'weekly',title:'Voie du combattant',desc:'Terminer 3 séances cette semaine',value:Math.min(3,h.filter(x=>Date.now()-new Date(x.date)<6048e5).length),max:3,xp:200,rarity:'RARE'},{id:'push',title:'Dépasser la limite',desc:'Atteindre 15 pompes',value:Math.min(15,Math.max(0,...h.flatMap(x=>x.records?.filter(r=>r.exercise==='Pompes').map(r=>r.reps)||[]))),max:15,xp:100,rarity:'ÉPIQUE'},{id:'enemy',title:'Chasseur d’ombres',desc:'Battre 5 ennemis',value:Math.min(5,enemies),max:5,xp:150,rarity:'RARE'},{id:'long',title:'La longue marche',desc:'Terminer 50 séances',value:Math.min(50,total),max:50,xp:500,rarity:'LÉGENDAIRE'}]}
function QuestLine({q,claim}){let done=q.value>=q.max;return <div className="quest-line"><div><b>{done?'✓':'◇'} {q.title}</b><small>{q.desc}</small></div><div className="quest-right"><span className={`rarity ${q.rarity}`}>{q.rarity}</span><Bar value={q.value} max={q.max}/><small>{q.value}/{q.max} · +{q.xp} XP</small>{claim&&done&&<button onClick={()=>claim(q)}>RÉCLAMER</button>}</div></div>}
function Quests({data,claim}){let achievements=[['PREMIER PAS','Terminer une séance','COMMUN',data.history.length>=1],['RÉGULARITÉ','Terminer 10 séances','RARE',data.history.length>=10],['PERSÉVÉRANT','Atteindre 7 jours de streak','ÉPIQUE',streak(data.history)>=7],['ASCENSION','Atteindre le niveau 50','LÉGENDAIRE',levelFor(data.xp).level>=50]];return <><Header label="TABLEAU DES QUÊTES"/><Frame className="quest-board">{questList(data).map(q=><QuestLine q={q} claim={claim} key={q.id}/>)}</Frame><h2 className="section-title">HAUTS FAITS</h2><div className="achievement-grid">{achievements.map(a=><Frame className={`achievement ${a[3]?'unlocked':''}`} key={a[0]}><span>✦</span><p className={`rarity ${a[2]}`}>{a[2]}</p><h3>{a[0]}</h3><small>{a[1]}</small></Frame>)}</div></>}
function MapPage({data}){let defeated=data.bossHp<=0;return <><Header label="CARTE DE L’ASCENSION" sub="SAISON 01 · LA CITADELLE OUBLIÉE"/><div className="map-layout"><Frame className="pixel-map"><div className="path path1"/><div className="path path2"/><div className="node start">▲<small>DÉPART</small></div><div className="node enemy">♟<small>OMBRE</small></div><div className="node enemy two">♟<small>GARDIEN</small></div><div className="node boss">♛<small>COLOSSE</small></div><div className="map-stars">✦　·　✧　·　✦</div></Frame><Frame className="boss-card"><p className="eyebrow">BOSS DE SAISON</p><PixelCharacter type="boss" size="large"/><h2>{defeated?'COLOSSE VAINCU':'LE COLOSSE'}</h2><p>Une ombre née des séances inachevées.</p><Bar value={data.bossHp} max={10000} color="var(--red)"/><b>{Math.max(0,data.bossHp).toLocaleString('fr-FR')} / 10 000 HP</b><div className="reward">RÉCOMPENSE · +{XP.boss} XP · TITRE ÉPIQUE</div></Frame></div><p className="map-note">Chaque séance convertit tes répétitions en dégâts contre les ténèbres.</p></>}
function Stats({data}){let h=data.history, sets=sum(h,'sets'), reps=sum(h,'reps'), mins=Math.round(sum(h,'duration')/60), records={};h.forEach(x=>x.records?.forEach(r=>records[r.exercise]=Math.max(records[r.exercise]||0,r.reps)));let stats=computeStats(h);return <><Header label="CHRONIQUES"/><div className="stat-cards">{[[h.length,'SÉANCES'],[sets,'SÉRIES'],[reps,'RÉPÉTITIONS'],[`${Math.floor(mins/60)}H${String(mins%60).padStart(2,'0')}`,'TEMPS DE COMBAT']].map(x=><Frame key={x[1]}><b>{x[0]}</b><small>{x[1]}</small></Frame>)}</div><div className="stats-grid"><Frame><div className="frame-title">ATTRIBUTS RPG</div>{Object.entries(stats).map(([k,v])=><div className="rpg-stat" key={k}><span>{k}</span><Bar value={v} color="var(--violet)"/><b>{v}</b></div>)}</Frame><Frame><div className="frame-title">RECORDS PERSONNELS</div>{Object.keys(records).length?Object.entries(records).map(([e,v])=><div className="record" key={e}><span>{e}</span><b>{v} reps</b></div>):<p className="empty">Tes exploits apparaîtront ici.</p>}</Frame></div><History data={data}/></>}
function computeStats(h){let reps=sum(h,'reps'), sets=sum(h,'sets'), base=Math.min(95,10+Math.floor(reps/25));return {FORCE:Math.min(99,10+Math.floor(reps/30)),ENDURANCE:Math.min(99,10+Math.floor(reps/22)),EXPLOSIVITÉ:Math.min(99,8+Math.floor(sets/4)),RÉSISTANCE:Math.min(99,10+Math.floor(sets/3)),DISCIPLINE:Math.min(99,10+h.length*3)}}
function History({data}){let [expanded,setExpanded]=useState(null);return <section className="history"><h2 className="section-title">JOURNAL D’ENTRAÎNEMENT</h2>{data.history.length?<div>{data.history.slice(0,6).map((x,i)=><Frame className="history-row" key={x.id} onClick={()=>setExpanded(expanded===i?null:i)}><span style={{color:COLORS[x.session.color]}}>{x.session.icon}</span><div><b>{x.session.name}</b><small>{new Date(x.date).toLocaleDateString('fr-FR',{day:'numeric',month:'long'})}</small></div><p>{x.sets} séries · {x.reps} reps</p><b>+{x.xp} XP</b>{expanded===i&&<div className="history-detail">{x.records.map((r,j)=><span key={j}>{r.exercise} · {r.reps} reps</span>)}</div>}</Frame>)}</div>:<Frame className="empty">Ton journal attend sa première victoire.</Frame>}</section>}
function Profile({data}){let lev=levelFor(data.xp), stats=computeStats(data.history);return <><Header label="LE HÉROS"/><div className="profile"><Frame className="profile-main"><PixelCharacter type="hero" size="large"/><div><span className="rank">{rankFor(lev.level)}</span><h2>NIVEAU {lev.level}</h2><p className="title-equip">« {data.title} »</p><Bar value={lev.inLevel} max={lev.need}/><small>{lev.inLevel}/{lev.need} XP pour le prochain niveau</small></div></Frame><Frame><div className="profile-totals"><div><b>🔥 {streak(data.history,data.restDays)}</b><small>STREAK</small></div><div><b>{data.xp}</b><small>XP TOTAL</small></div><div><b>{data.history.length}</b><small>ÉPREUVES</small></div></div></Frame><Frame><div className="frame-title">ATTRIBUTS</div>{Object.entries(stats).map(([k,v])=><div className="rpg-stat" key={k}><span>{k}</span><Bar value={v}/><b>{v}</b></div>)}</Frame></div></>}
function streak(history,restDays=[0,2,4,6]){if(!history.length)return 0;let done=new Set(history.map(x=>new Date(x.date).toDateString())),cursor=new Date(Math.max(...history.map(x=>new Date(x.date))));cursor.setHours(0,0,0,0);let count=0;for(let i=0;i<365;i++){if(done.has(cursor.toDateString())||restDays.includes(cursor.getDay()))count++;else break;cursor.setDate(cursor.getDate()-1)}return count}
function App(){let [data,setData]=useState(load),[page,setPage]=useState('home'),[active,setActive]=useState(null),[result,setResult]=useState(null);useEffect(()=>save(data),[data]);const start=s=>{setActive(s);setPage('training')};const finish=(session,records)=>{let reps=sum(records,'reps'), sets=records.length, damage=Math.max(250,reps*8), stat=records[0]?.stat||'Force', xp=sets*XP.series+session.blocks.filter(b=>b.rest>0).length*XP.block+XP.session;let proposals={...data.proposals};session.blocks.flatMap(b=>b.ex).forEach(e=>{let current=proposals[e[0]]||Array(e[1]).fill(e[2]), performed=records.filter(r=>r.exercise===e[0]);if(performed.length===e[1]&&performed.every((r,i)=>r.reps>=current[i])){let p=current.findIndex((n,i)=>n<e[3]&&(i===0||current[i-1]>=n));if(p>=0)current=current.map((n,i)=>i===p?n+1:n)}proposals[e[0]]=current});let entry={id:Date.now(),date:new Date().toISOString(),session,records,reps,sets,duration:Math.max(60,sets*55),xp};let newData={...data,xp:data.xp+xp,history:[entry,...data.history],bossHp:Math.max(0,data.bossHp-damage),proposals};setData(newData);setResult({session,records,xp,damage,streak:streak(newData.history),stat,statGain:Math.max(1,Math.floor(reps/35))});setActive(null);setPage('results')};const claim=q=>{if(data.claimed.includes(q.id))return;setData({...data,xp:data.xp+q.xp,claimed:[...data.claimed,q.id]})};let content=page==='home'?<Dashboard data={data} start={start}/>:page==='sessions'?<Sessions start={start} data={data}/>:page==='training'?<Training session={active} finish={finish} back={()=>setPage('sessions')} data={data}/>:page==='results'?<Results result={result} continueTo={()=>setPage('home')}/>:page==='stats'?<Stats data={data}/>:page==='map'?<MapPage data={data}/>:page==='quests'?<Quests data={data} claim={claim}/>:<Profile data={data}/>;if(['training','results'].includes(page))return content;return <Layout page={page} setPage={setPage} data={data}>{content}</Layout>}
createRoot(document.getElementById('root')).render(<App/>);
